### ISSUE TITLE
Adding Prosis Pro to Active Member

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#10]
I tried to add Prosis Pro to an active member, after selected Single and put "test" inside note and click Save. None of the information has been save. 
<img width="1093" alt="screen shot 2017-02-23 at 6 30 54 pm" src="https://cloud.githubusercontent.com/assets/7178461/23288116/60059e1e-f9f6-11e6-8b99-67622f8bd33b.png">
<img width="1082" alt="screen shot 2017-02-23 at 6 31 02 pm" src="https://cloud.githubusercontent.com/assets/7178461/23288117/6008aa8c-f9f6-11e6-97cd-290c2081b57b.png">

**Comment by sagarjagdish** [comment]
@omnitekinc : Annual fees required to inset record into Prosis Pro. Please let me know if we need to remove that validation. 

You can try with Annual fees and record will be added.

**Comment by omnitekinc** [comment]
This is working now. Will do more testing but I will close this ticket for now.
