### ISSUE TITLE
Prosis Pro Pricing Update

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#11]
We need to update the Prosis Pro Pricing into the 6 category from the pricing excel from AERA, and also change it to a drop down instead of radio button. Please make sure when selected the plan the price is updated automatically just like membership.

**Comment by sagarjagdish** [comment]
@omnitekinc  :  We have implemented new price structure related feature for Prosis Pro and now it's on stage.

We have also updated all the existing Prosis Pro users based on current activation. Please check and confirm. 

<img width="771" alt="prosis-pro-new-setup" src="https://cloud.githubusercontent.com/assets/7322922/23307229/cc3e19c2-facc-11e6-8816-f4654d53dbd6.png">
