### ISSUE TITLE
PDF Invoice, address format Wrong.

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#12]
Can you update the addresses for both AERA and the member, the format is weird, missint "," and zip code. 
<img width="815" alt="screen shot 2017-02-23 at 6 34 30 pm" src="https://cloud.githubusercontent.com/assets/7178461/23288264/523fa53a-f9f7-11e6-9550-9c27267c1b49.png">

**Comment by sagarjagdish** [comment]
@omnitekinc  : did this change and uploaded on stage. please verify.

http://71.13.159.202/aeramms_stage/addnewmember.aspx?id=6114&mode=view&searchterm=2196
