### ISSUE TITLE
Date filter showing wrong result

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#13]
I selected the start date 02/02/1990, the first result was the test account I created, it showed up. It shouldn't show up because it was created in 2017.

<img width="1071" alt="screen shot 2017-02-23 at 6 45 26 pm" src="https://cloud.githubusercontent.com/assets/7178461/23288405/4d57482e-f9f8-11e6-9ca7-601af493d22e.png">

**Comment by sagarjagdish** [comment]
@omnitekinc : earlier it's working based on start date and expiry date. now we updated login as per your above expectation. now this logic will work on join date.

Please verify and let me know if any change required in this.

**Comment by omnitekinc** [comment]
Hi Sagar,
Can you explain the logic to me? If I put in "Start Date" 01-01-2010, it's going to show me all the members that Join on 01-01-2010?

**Comment by sagarjagdish** [comment]
Hi Stella,

If you put Start Date 01-01-2010 then it's show all the users having Join Date 01-01-2010 and greater than 01-01-201 as end date it blank.

If you put Start Date 01-01-2010 and End Date 31-01-2010 then it will show only those users who joined between that date.

If you put only End Date 31-01-2010 then it will show all the users who joined before  31-01-2010 date as Start Date blank.

**Comment by omnitekinc** [comment]
Hi Sagar,
I just tested this but I am not getting any results. Can you please take a look.
![screen shot 2017-03-01 at 10 08 41 am](https://cloud.githubusercontent.com/assets/7178461/23473984/10172f56-fe67-11e6-8580-ab87bea4565d.png)

**Comment by sagarjagdish** [comment]
It's working now. There is issue with last upload. membership search stop working and we resolved but not upload change on stage so you faced this issue.

I have resolved this issue on stage now and it's working fine as per my explanation. Please check.
