### ISSUE TITLE
Email Invoice Information Missing

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#14]
Here is the email I received:
1. Date:##DATE1##, it should put a real date
2. 875 Feinberg Ct, Ste 106
Cary, IL 60013 (need a "," after Cary)
---------------------------------
Dear Member,
Annual Membership Service Fee Service Agreement are due, to continue service please renew your membership and Prosis Pro.
Date:##DATE1##	Amount Due: $529.00
Total Amount Due: $529.00
Renew online:
www.aera.org
By Mail:
875 Feinberg Ct, Ste 106
Cary IL 60013
Please see attached invoice for full details, or contact us if you have any questions.

**Comment by sagarjagdish** [comment]
@omnitekinc  : Please let us know which date you would like to replace ##DATE1##. expiry date or current date (invoice sent date).

I have read PFD that given by you and there you mentioned like "Due Date: Dynamically generated based on each member. " , question is on which based we have to generate dynamically? Is there any formula to generate due date for invoice?

<img width="785" alt="invoice-dues-date" src="https://cloud.githubusercontent.com/assets/7322922/23290694/c67423fa-fa78-11e6-91ee-292abc10cb0f.png">

**Comment by omnitekinc** [comment]
Let's just change ##DATE1## to Expiration Date: ##DATE1##
For both email and pdf. Keeping it simple.

**Comment by sagarjagdish** [comment]
We changed date with "Expiration Date" and uploaded on stage, please verify and confirm.
