### ISSUE TITLE
Phone/Fax # Same Format

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#15]
Can we make sure ALL numbers are in the same format? Right now some have "-" and some
![screen shot 2017-02-24 at 8 34 31 am](https://cloud.githubusercontent.com/assets/7178461/23311804/3b1405e8-fa6c-11e6-970d-4623f4456826.png)
 don't.

**Comment by sagarjagdish** [comment]
@omnitekinc  : We done for both Phone & Fax and uploaded on stage. Please verify.
