### ISSUE TITLE
Country in Address is Missing United State of America

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#17]
There's no United State of America in the country dropdown. Can we set USA as a default option.
![screen shot 2017-02-24 at 8 48 45 am](https://cloud.githubusercontent.com/assets/7178461/23312324/296a3658-fa6e-11e6-8ce7-5095f30e09f7.png)

**Comment by sagarjagdish** [comment]
@omnitekinc  : added USA and also updated all existing membership where USA state is selected. Please verify and confirm.

**Comment by omnitekinc** [comment]
In the drop down, can you make USA the first one instead of the last one

**Comment by sagarjagdish** [comment]
@omnitekinc : done and uploaded on stage.
