### ISSUE TITLE
Tech Queue

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#18]
Sagar, Where is the Tech Queue data? I saw it on the staging site that only has 4 entries.

**Comment by sagarjagdish** [comment]
@omnitekinc  : I have checked and there is only 4 open call and all other are closed. so you see closed call under "Close Call" tab.

**Comment by omnitekinc** [comment]
I see so you also imported the closed calls to the closed call tab right?

**Comment by sagarjagdish** [comment]
Yes, imported all data with close call.
