### ISSUE TITLE
 Contributions and Discounts don't update membership

### ISSUE THREAD

**Issue by karltonfrazier** [omnitekinc/AERA_MSS#20]
![screen shot 2017-02-26 at 9 11 59 pm](https://cloud.githubusercontent.com/assets/4383088/23349480/7ad63d92-fc68-11e6-8c7f-00f2222d0503.png)

**Comment by sagarjagdish** [comment]
@karltonfrazier : member due different from all those calculation, I have checked existing system and found  "Amount Accrued" field where they are showing price including contribution & minus discount.

I have added same field to show "Amount Accrued".

<img width="772" alt="accrued-amount" src="https://cloud.githubusercontent.com/assets/7322922/23362318/3c041c8e-fd1b-11e6-8720-dc99dbcfd8dc.png">

**Comment by sagarjagdish** [comment]
@omnitekinc : Please let me know which action required here from my end?

**Comment by omnitekinc** [comment]
I checked this, and it looks like the math is working in the system but when I generate an invoice, it only show membership.
![screen shot 2017-03-01 at 10 41 33 am](https://cloud.githubusercontent.com/assets/7178461/23475281/ea515c74-fe6b-11e6-9e52-17d0445e5ee1.png)
![screen shot 2017-03-01 at 10 41 38 am](https://cloud.githubusercontent.com/assets/7178461/23475289/ec6fe930-fe6b-11e6-98a5-13035adcb239.png)

**Comment by sagarjagdish** [comment]
@omnitekinc : You mean like we need to show contribution, discount inside invoice as well, correct?

Please see attached document for the my query. We need your comment before taking action on this.

[Invoice-Dues-Query.docx](https://github.com/omnitekinc/AERA_MSS/files/813547/Invoice-Dues-Query.docx)

**Comment by omnitekinc** [comment]
Yes of course, the invoice is being sent to the member so they know how much they should pay, so it needs to match the record.
