### ISSUE TITLE
Mandatory Address

### ISSUE THREAD

**Issue by karltonfrazier** [omnitekinc/AERA_MSS#21]
Need to make address mandatory. If you don't, and generate an invoice, you get this.

![screen shot 2017-02-26 at 9 12 35 pm](https://cloud.githubusercontent.com/assets/4383088/23349551/0974562e-fc69-11e6-9ae5-e0fc1107ecb7.png)

**Comment by omnitekinc** [comment]
I need to check with client on this one

**Comment by omnitekinc** [comment]
Let's just leave this as is for now.
