### ISSUE TITLE
UI Change

### ISSUE THREAD

**Issue by karltonfrazier** [omnitekinc/AERA_MSS#22]
Either Raise the button 1 pixel, or change the color of the top line

https://www.evernote.com/shard/s654/sh/c8e63701-9903-4af2-9a71-b005995faa1d/5599d1271b22278040587776099d53e2

**Comment by omnitekinc** [comment]
Karlton, this one is fine. That's how the button looks like in the design. But we can make it low priority

**Comment by omnitekinc** [comment]
Karlton, if you want sagar to update the design of this button, please mock it up for him so he knows how it should look.

**Comment by sagarjagdish** [comment]
@karltonfrazier : Please let me know which change required here and what should I have to do with this change.
