### ISSUE TITLE
Search Not Fully Functional

### ISSUE THREAD

**Issue by karltonfrazier** [omnitekinc/AERA_MSS#24]
![screen shot 2017-02-26 at 9 38 24 pm](https://cloud.githubusercontent.com/assets/4383088/23349968/0081a38e-fc6c-11e6-8e25-42b75b0cb9a8.png)

**Comment by sagarjagdish** [comment]
@karltonfrazier : resolved this issue on stage. Please verify and confirm.

**Comment by karltonfrazier** [comment]
working

**Comment by omnitekinc** [comment]
I actually tried this and it's not working for me.

**Comment by sagarjagdish** [comment]
@omnitekinc  : It's working now. there is some issue with last upload which we did so it's stop working again when you did testing. We have already resolved that issue in local but not uploaded on stage so you faced with that.

now it's working fine.
