### ISSUE TITLE
Change Subject Line

### ISSUE THREAD

**Issue by karltonfrazier** [omnitekinc/AERA_MSS#28]
Take out "Dear" - Ask Stella for Default title

![screen shot 2017-02-27 at 11 43 05 am](https://cloud.githubusercontent.com/assets/4383088/23449262/7b9593f6-fe0a-11e6-8ad3-f19e49623792.png)

**Comment by karltonfrazier** [comment]
Leave Title empty

**Comment by sagarjagdish** [comment]
done. now subject like is blank for prospect email. please verify on stage.
