### ISSUE TITLE
Edit Membership & Save

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#3]
After editing membership, and then click Save button, the page reload and took me back to the Membership listing page.

Expectation: After clicked save, it should show me the non-editing view of the member detail.

**Comment by sagarjagdish** [comment]
@omnitekinc  : We have already implemented this function before but previously informed us to redirect on list page. This issue listed inside google sheet.

anyway we will again make same which we did before, show non-editing view of the member when user click on save.

**Comment by sagarjagdish** [comment]
@karltonfrazier  / @omnitekinc  : We did change as suggested and now showing non-editing view of member when user click on save and uploaded on stage.

Please verify and confirm.

**Comment by omnitekinc** [comment]
But if I save now, it just stayed on the edit page. Where it should be view mode, like the image
![screen shot 2017-02-22 at 9 19 20 am](https://cloud.githubusercontent.com/assets/7178461/23223517/2044f1b0-f8e0-11e6-8262-1e05c490ec63.png)

**Comment by sagarjagdish** [comment]
It's done but you can't see only because of save button not working. I have corrected that data and now it's working. Please check.
