### ISSUE TITLE
Tech Queue - Email PDF attachment error

### ISSUE THREAD

**Issue by karltonfrazier** [omnitekinc/AERA_MSS#30]
Only selected 1 attachment

![screen shot 2017-03-03 at 1 48 55 pm](https://cloud.githubusercontent.com/assets/4383088/23570258/4303659e-0018-11e7-8f37-ead1af40947a.png)

**Comment by sagarjagdish** [comment]
@karltonfrazier : I have tried to reproduce this issue on stage but it's working fine for me. could you please provide me specific list of step to generate this error?

Please see below image, it's working for me. I uses same member from tech call which taken by you to test.

<img width="773" alt="pdf_issue_tech_call" src="https://cloud.githubusercontent.com/assets/7322922/23578263/ce385666-00f8-11e7-923d-7495c4ddf6a9.png">

**Comment by omnitekinc** [comment]
It's working beautifully!
