### ISSUE TITLE
Add ability to search Tech Queue by Name and Email 

### ISSUE THREAD

**Issue by karltonfrazier** [omnitekinc/AERA_MSS#34]
If I search via the name or email, no results show up

![screen shot 2017-03-03 at 2 20 31 pm](https://cloud.githubusercontent.com/assets/4383088/23571335/868c28aa-001d-11e7-87e5-9a2ef41815c3.png)
![screen shot 2017-03-03 at 2 21 55 pm](https://cloud.githubusercontent.com/assets/4383088/23571337/8954be4e-001d-11e7-9965-5601358bce38.png)
![screen shot 2017-03-03 at 2 22 25 pm](https://cloud.githubusercontent.com/assets/4383088/23571340/8e0cb0ae-001d-11e7-9e69-f60d645d0420.png)
![screen shot 2017-03-03 at 2 23 24 pm](https://cloud.githubusercontent.com/assets/4383088/23571342/90c0b98a-001d-11e7-9029-d3f4b5d6c82d.png)

**Comment by sagarjagdish** [comment]
Implemented both name and email search on stage for close call. 
<img width="776" alt="email-search" src="https://cloud.githubusercontent.com/assets/7322922/23578454/4d718d54-00fd-11e7-884b-9a74e3151381.png">
<img width="770" alt="name-search" src="https://cloud.githubusercontent.com/assets/7322922/23578455/4d98a57e-00fd-11e7-9dc3-9d2e4c6801f9.png">
