### ISSUE TITLE
Create New Tech Call Save Error

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#37]
I got this error when I try to save a new tech call.

![screen shot 2017-03-08 at 3 42 33 pm](https://cloud.githubusercontent.com/assets/7178461/23729287/e5f0f69e-0415-11e7-8688-1c08eeadcd47.png)

**Comment by sagarjagdish** [comment]
@omnitekinc  : We have resolved this error and uploaded on stage. Please verify and confirm that issue is resolved now.

**Comment by omnitekinc** [comment]
When creating a new call, can we default the status to NEW. 
![screen shot 2017-03-09 at 9 02 34 am](https://cloud.githubusercontent.com/assets/7178461/23761312/3f0ad754-04a7-11e7-8fe2-a90cc288da5c.png)

**Comment by sagarjagdish** [comment]
@omnitekinc  : done and uploaded on stage. Please verify and confirm.
