### ISSUE TITLE
Testing Account

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#38]
Can we create test account for the following user:

Chuck Lynch
Dave Hagen
Jim Rickoff
Karen Tendering
Amanda Harmening

**Comment by sagarjagdish** [comment]
@omnitekinc  : Please see below for the list login detail.

http://71.13.159.202/aeramms_stage/login.aspx

Chuck Lynch >> CL/test123
Dave Hagen >> DH/test123
Jim Rickoff >> JR/test123
Karen Tendering >> KT/test123
Amanda Harmening >> AH/test123
