### ISSUE TITLE
Error Message after adding the 2nd & 3rd contact phone number

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#4]
Edit any member in the detail page
When adding phone numbers to additional contact (either one)
Clicked Save
Go back to the detail screen and click Edit get an error message
It has to do with the **phone number field**, I tried it with First, Last name and email and this error didn't occur. Check member: 2196, 8500 & 9553
<img width="1393" alt="screen shot 2017-02-21 at 9 39 19 pm" src="https://cloud.githubusercontent.com/assets/7178461/23198801/ef3b0e26-f87e-11e6-98b6-5073a4f6cfc0.png">

**Comment by sagarjagdish** [comment]
@karltonfrazier  : We have resolved this issue and uploaded on stage. Please verify and confirm.

**Comment by omnitekinc** [comment]
Can't test this because the Save button is not working.

**Comment by sagarjagdish** [comment]
There is some issue with old data. I have correct. You can test now.
