### ISSUE TITLE
Clear Search Button

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#7]
Can we add a clear search button, and when click, it will just clear all the search option?
<img width="1062" alt="screen shot 2017-02-23 at 6 17 46 pm" src="https://cloud.githubusercontent.com/assets/7178461/23287896/24c460e8-f9f5-11e6-8df5-f989cf4646b1.png">

**Comment by sagarjagdish** [comment]
@omnitekinc  : added "Clear" button as shown and uploaded on stage.
