### ISSUE TITLE
Membership Search, Phone number with no result

### ISSUE THREAD

**Issue by omnitekinc** [omnitekinc/AERA_MSS#8]
I tried to search for a member phone number:
361-576-5759 and tried 3615765759
But no result show up

**Comment by sagarjagdish** [comment]
@omnitekinc : now searching on phone# working fine on stage with both format 361-576-5759 and 3615765759

http://71.13.159.202/aeramms_stage/membership.aspx?searchterm=361-576-5759

http://71.13.159.202/aeramms_stage/membership.aspx?searchterm=3615765759
